
spring:
  #datasource configurations
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.fkpdcoqsiuqabmilgmok&password=Vedant@9637
    username: postgres.fkpdcoqsiuqabmilgmok
    password: Vedant@9637
    driver-class-name: org.postgresql.Driver

  #jpa configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
